<?php

namespace Ecentinela\ComiconvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversionRepository extends EntityRepository
{
}